### ISSUE TITLE
Crash while cloning through ssh with username/password

### ISSUE THREAD

**Issue by gabm** [android-password-store/Android-Password-Store#108]
Unfortunately I get a crash whenever I clone a repository through ssh with username/password (public key auth doesn't work on this server)..

here is a log, it seems a class from org.ietf.jgss is missing?! I used the latest master version on Android 5.1.1

```
07-24 23:43:48.643  27836-27964/com.zeapo.pwdstore W/art﹕ Unresolved exception class when finding catch block: org.ietf.jgss.GSSException
07-24 23:43:48.649  27836-27964/com.zeapo.pwdstore E/AndroidRuntime﹕ FATAL EXCEPTION: AsyncTask #1
    Process: com.zeapo.pwdstore, PID: 27836
    java.lang.RuntimeException: An error occured while executing doInBackground()
            at android.os.AsyncTask$3.done(AsyncTask.java:304)
            at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
            at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
            at java.util.concurrent.FutureTask.run(FutureTask.java:242)
            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
     Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lorg/ietf/jgss/Oid;
            at com.jcraft.jsch.jgss.GSSContextKrb5.create(GSSContextKrb5.java:55)
            at com.jcraft.jsch.UserAuthGSSAPIWithMIC.start(UserAuthGSSAPIWithMIC.java:125)
            at com.jcraft.jsch.Session.connect(Session.java:463)
            at org.eclipse.jgit.transport.JschConfigSessionFactory.getSession(JschConfigSessionFactory.java:116)
            at org.eclipse.jgit.transport.SshTransport.getSession(SshTransport.java:136)
            at org.eclipse.jgit.transport.TransportGitSsh$SshFetchConnection.<init>(TransportGitSsh.java:262)
            at org.eclipse.jgit.transport.TransportGitSsh.openFetch(TransportGitSsh.java:161)
            at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:136)
            at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:122)
            at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1138)
            at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:130)
            at org.eclipse.jgit.api.CloneCommand.fetch(CloneCommand.java:193)
            at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:133)
            at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:83)
            at com.zeapo.pwdstore.git.GitAsyncTask.doInBackground(GitAsyncTask.java:44)
            at com.zeapo.pwdstore.git.GitAsyncTask.doInBackground(GitAsyncTask.java:18)
            at android.os.AsyncTask$2.call(AsyncTask.java:292)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "org.ietf.jgss.Oid" on path: DexPathList[[zip file "/data/app/com.zeapo.pwdstore-2/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
            at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
            at com.jcraft.jsch.jgss.GSSContextKrb5.create(GSSContextKrb5.java:55)
            at com.jcraft.jsch.UserAuthGSSAPIWithMIC.start(UserAuthGSSAPIWithMIC.java:125)
            at com.jcraft.jsch.Session.connect(Session.java:463)
            at org.eclipse.jgit.transport.JschConfigSessionFactory.getSession(JschConfigSessionFactory.java:116)
            at org.eclipse.jgit.transport.SshTransport.getSession(SshTransport.java:136)
            at org.eclipse.jgit.transport.TransportGitSsh$SshFetchConnection.<init>(TransportGitSsh.java:262)
            at org.eclipse.jgit.transport.TransportGitSsh.openFetch(TransportGitSsh.java:161)
            at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:136)
            at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:122)
            at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1138)
            at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:130)
            at org.eclipse.jgit.api.CloneCommand.fetch(CloneCommand.java:193)
            at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:133)
            at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:83)
            at com.zeapo.pwdstore.git.GitAsyncTask.doInBackground(GitAsyncTask.java:44)
            at com.zeapo.pwdstore.git.GitAsyncTask.doInBackground(GitAsyncTask.java:18)
            at android.os.AsyncTask$2.call(AsyncTask.java:292)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
    Suppressed: java.lang.ClassNotFoundException: org.ietf.jgss.Oid
            at java.lang.Class.classForName(Native Method)
            at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
            at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
            ... 23 more
     Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
07-24 23:43:48.695  27836-27836/com.zeapo.pwdstore D/REPO﹕ current path: /data/data/com.zeapo.pwdstore/files/store
07-24 23:43:48.695  27836-27836/com.zeapo.pwdstore D/PASS﹕ Check, dir: /data/data/com.zeapo.pwdstore/files/store
07-24 23:43:48.783  27836-27836/com.zeapo.pwdstore I/Timeline﹕ Timeline: Activity_idle id: android.os.BinderProxy@3187a62d time:6169260
07-24 23:43:49.073  27836-27836/com.zeapo.pwdstore E/WindowManager﹕ android.view.WindowLeaked: Activity com.zeapo.pwdstore.git.GitActivity has leaked window com.android.internal.policy.impl.PhoneWindow$DecorView{103e27c3 V.E..... R......D 0,0-1026,348} that was originally added here
            at android.view.ViewRootImpl.<init>(ViewRootImpl.java:363)
            at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:271)
            at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:85)
            at android.app.Dialog.show(Dialog.java:298)
            at com.zeapo.pwdstore.git.GitAsyncTask.onPreExecute(GitAsyncTask.java:37)
            at android.os.AsyncTask.executeOnExecutor(AsyncTask.java:591)
            at android.os.AsyncTask.execute(AsyncTask.java:539)
            at com.zeapo.pwdstore.git.CloneOperation.execute(CloneOperation.java:65)
            at com.zeapo.pwdstore.git.GitOperation$7.onClick(GitOperation.java:178)
            at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:162)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5289)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
```

Please tell me if I can help u further...

**Comment by Aeyoun** [comment]
I’m having the same issue. Nothing to weird with my setup, I think. Android 6, IPv4 and 6, …

**Comment by Aeyoun** [comment]
Google Play and F-Droid distribution alike …

**Comment by Aeyoun** [comment]
Just had the same crash on my new Nexus 5X with up-to-date Android 6.0.1 as well. Previous report was from Sony Xperia Z3 with Sony Concept Software (Android 6).

**Comment by Aeyoun** [comment]
This seems to be a proguard issue, see https://stackoverflow.com/questions/19544966/cant-enable-proguard-on-android-project-containing-jsch-lib

**Comment by Kirupakaran** [comment]
I'm having the same issue.

**Comment by zeapo** [comment]
@Kirupakaran what version of the app? Could you provide the log please?

**Comment by Kirupakaran** [comment]
@zeapo I'm using v1.2.0.64 in s6e running android 7.0. After I click clone and provide password, app crashes. I'll try to provide logs soon.

**Comment by travisjayday** [comment]
Same issue here. Sad that there's no fix since my server requires Kerberos 5 :-(

**Comment by msfjarvis** [comment]
Is this still an issue on the [latest snapshot](https://dl.msfjarvis.dev/APS)?

**Comment by msfjarvis** [comment]
Closing until someone can confirm the bug exists on master.
