### ISSUE TITLE
Crash when opening "App and website settings"

### ISSUE THREAD

**Issue by ashkitten** [android-password-store/Android-Password-Store#381]
Backtrace:

```
02-17 08:47:44.267 9290-10018/? E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
                                                  Process: com.zeapo.pwdstore, PID: 9290
                                                  java.lang.RuntimeException: An error occurred while executing doInBackground()
                                                      at android.os.AsyncTask$3.done(AsyncTask.java:318)
                                                      at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
                                                      at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
                                                      at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                      at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
                                                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                      at java.lang.Thread.run(Thread.java:762)
                                                   Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.toLowerCase()' on a null object reference
                                                      at com.zeapo.pwdstore.autofill.AutofillRecyclerAdapter$1.compare(AutofillRecyclerAdapter.java:79)
                                                      at com.zeapo.pwdstore.autofill.AutofillRecyclerAdapter$1.compare(AutofillRecyclerAdapter.java:74)
                                                      at android.support.v7.util.SortedList$BatchedCallback.compare(SortedList.java:780)
                                                      at java.util.TimSort.binarySort(TimSort.java:296)
                                                      at java.util.TimSort.sort(TimSort.java:239)
                                                      at java.util.Arrays.sort(Arrays.java:1450)
                                                      at android.support.v7.util.SortedList.addAllInternal(SortedList.java:198)
                                                      at android.support.v7.util.SortedList.addAll(SortedList.java:156)
                                                      at android.support.v7.util.SortedList.addAll(SortedList.java:185)
                                                      at com.zeapo.pwdstore.autofill.AutofillRecyclerAdapter.<init>(AutofillRecyclerAdapter.java:93)
                                                      at com.zeapo.pwdstore.autofill.AutofillPreferenceActivity$populateTask.doInBackground(AutofillPreferenceActivity.java:106)
                                                      at com.zeapo.pwdstore.autofill.AutofillPreferenceActivity$populateTask.doInBackground(AutofillPreferenceActivity.java:74)
                                                      at android.os.AsyncTask$2.call(AsyncTask.java:304)
                                                      at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                      at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243) 
                                                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
                                                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
                                                      at java.lang.Thread.run(Thread.java:762)
```

**Comment by msfjarvis** [comment]
We have released a new Autofill implementation for Android Oreo and above users which supersedes and deprecates the version this problem affects. Closing.
