### ISSUE TITLE
[BUG] Crash java.lang.ClassNotFoundException: org.openintents.openpgp.OpenPgpError

### ISSUE THREAD

**Issue by pdecat** [android-password-store/Android-Password-Store#614]
**Describe the bug**

App crash when trying to read a secret:

```
01-25 10:56:17.863  1336  2133 I ActivityTaskManager: START u0 {cmp=dev.msfjarvis.aps/com.zeapo.pwdstore.crypto.PgpActivity (has extras)} from uid 10363
01-25 10:56:17.864   902   902 D android.hardware.power@1.3-service.pixel-libperfmgr: LAUNCH: 1
01-25 10:56:17.882 23905 23905 W ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@485fa38
01-25 10:56:17.906 23905 23919 W System  : A resource failed to call end.
01-25 10:56:17.906 23905 23919 W System  : A resource failed to call end.
01-25 10:56:17.959 23905 23905 E Parcel  : Class not found when unmarshalling: org.openintents.openpgp.OpenPgpError
01-25 10:56:17.959 23905 23905 E Parcel  : java.lang.ClassNotFoundException: org.openintents.openpgp.OpenPgpError
01-25 10:56:17.959 23905 23905 E Parcel  :      at java.lang.Class.classForName(Native Method)
01-25 10:56:17.959 23905 23905 E Parcel  :      at java.lang.Class.forName(Class.java:454)
01-25 10:56:17.959 23905 23905 E Parcel  :      at android.os.Parcel.readParcelableCreator(Parcel.java:3014)
01-25 10:56:17.959 23905 23905 E Parcel  :      at android.os.Parcel.readParcelable(Parcel.java:2964)
01-25 10:56:17.959 23905 23905 E Parcel  :      at android.os.Parcel.readValue(Parcel.java:2866)
01-25 10:56:17.959 23905 23905 E Parcel  :      at android.os.Parcel.readArrayMapInternal(Parcel.java:3244)
01-25 10:56:17.959 23905 23905 E Parcel  :      at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:292)
01-25 10:56:17.959 23905 23905 E Parcel  :      at android.os.BaseBundle.unparcel(BaseBundle.java:236)
01-25 10:56:17.959 23905 23905 E Parcel  :      at android.os.BaseBundle.getInt(BaseBundle.java:1035)
01-25 10:56:17.959 23905 23905 E Parcel  :      at android.content.Intent.getIntExtra(Intent.java:7835)
01-25 10:56:17.959 23905 23905 E Parcel  :      at com.zeapo.pwdstore.crypto.PgpActivity$decryptAndVerify$1$1.onReturn(PgpActivity.kt:1)
01-25 10:56:17.959 23905 23905 E Parcel  :      at me.msfjarvis.openpgpktx.util.OpenPgpApi$executeApiAsync$2.invokeSuspend(OpenPgpApi.kt:3)
01-25 10:56:17.959 23905 23905 E Parcel  :      at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:2)
01-25 10:56:17.959 23905 23905 E Parcel  :      at kotlinx.coroutines.DispatchedContinuation.run(Dispatched.kt:19)
01-25 10:56:17.959 23905 23905 E Parcel  :      at android.os.Handler.handleCallback(Handler.java:883)
01-25 10:56:17.959 23905 23905 E Parcel  :      at android.os.Handler.dispatchMessage(Handler.java:100)
01-25 10:56:17.959 23905 23905 E Parcel  :      at android.os.Looper.loop(Looper.java:214)
01-25 10:56:17.959 23905 23905 E Parcel  :      at android.app.ActivityThread.main(ActivityThread.java:7356)
01-25 10:56:17.959 23905 23905 E Parcel  :      at java.lang.reflect.Method.invoke(Native Method)
01-25 10:56:17.959 23905 23905 E Parcel  :      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
01-25 10:56:17.959 23905 23905 E Parcel  :      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
01-25 10:56:17.959 23905 23905 E Parcel  : Caused by: java.lang.ClassNotFoundException: org.openintents.openpgp.OpenPgpError
01-25 10:56:17.959 23905 23905 E Parcel  :      ... 21 more
01-25 10:56:17.960   902   902 D android.hardware.power@1.3-service.pixel-libperfmgr: LAUNCH: 0
01-25 10:56:17.960 23905 23937 E AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-1
01-25 10:56:17.960 23905 23937 E AndroidRuntime: Process: dev.msfjarvis.aps, PID: 23905
01-25 10:56:17.960 23905 23937 E AndroidRuntime: android.os.BadParcelableException: ClassNotFoundException when unmarshalling: org.openintents.openpgp.OpenPgpError
01-25 10:56:17.960 23905 23937 E AndroidRuntime:        at android.os.Parcel.readParcelableCreator(Parcel.java:3042)
01-25 10:56:17.960 23905 23937 E AndroidRuntime:        at android.os.Parcel.readParcelable(Parcel.java:2964)
01-25 10:56:17.960 23905 23937 E AndroidRuntime:        at android.os.Parcel.readValue(Parcel.java:2866)
01-25 10:56:17.960 23905 23937 E AndroidRuntime:        at android.os.Parcel.readArrayMapInternal(Parcel.java:3244)
01-25 10:56:17.960 23905 23937 E AndroidRuntime:        at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:292)
01-25 10:56:17.960 23905 23937 E AndroidRuntime:        at android.os.BaseBundle.unparcel(BaseBundle.java:236)
01-25 10:56:17.960 23905 23937 E AndroidRuntime:        at android.os.BaseBundle.getInt(BaseBundle.java:1035)
01-25 10:56:17.960 23905 23937 E AndroidRuntime:        at android.content.Intent.getIntExtra(Intent.java:7835)
01-25 10:56:17.960 23905 23937 E AndroidRuntime:        at com.zeapo.pwdstore.crypto.PgpActivity$decryptAndVerify$1$1.onReturn(PgpActivity.kt:1)
01-25 10:56:17.960 23905 23937 E AndroidRuntime:        at me.msfjarvis.openpgpktx.util.OpenPgpApi$executeApiAsync$2.invokeSuspend(OpenPgpApi.kt:3)
01-25 10:56:17.960 23905 23937 E AndroidRuntime:        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:2)
01-25 10:56:17.960 23905 23937 E AndroidRuntime:        at kotlinx.coroutines.DispatchedContinuation.run(Dispatched.kt:19)
01-25 10:56:17.960 23905 23937 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:883)
01-25 10:56:17.960 23905 23937 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:100)
01-25 10:56:17.960 23905 23937 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:214)
01-25 10:56:17.960 23905 23937 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7356)
01-25 10:56:17.960 23905 23937 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
01-25 10:56:17.960 23905 23937 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
01-25 10:56:17.960 23905 23937 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
01-25 10:56:17.963  1336 23942 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
01-25 10:56:17.964  1336  2236 W ActivityTaskManager:   Force finishing activity dev.msfjarvis.aps/com.zeapo.pwdstore.crypto.PgpActivity
```

**To Reproduce**
1. Go to the main view
2. Click on a secret
3. App crashes and is forced closed.

**Expected behavior**

Secret should show decrypted.

**Screenshots**

**Device information:**
 - Device: Google Pixel 3 XL
 - OS: stock ROM Android version 10.0
 - App version 1.4.0 from https://play.google.com/store/apps/details?id=dev.msfjarvis.aps

**Additional context**

Using OpenKeyChain to git clone SSH and decrypt PGP encrypted secrets.

**Comment by msfjarvis** [comment]
I was pretty sure I fixed this :/
Will take a look alongwith the other reported problems.

**Comment by msfjarvis** [comment]
Can you test if https://dl.msfjarvis.dev/temp/app-release.apk fixes the problem for you?

**Comment by pdecat** [comment]
Still the same error with 1.5.0-SNAPSHOT:

```
01-25 14:50:48.891   902   902 D android.hardware.power@1.3-service.pixel-libperfmgr: LAUNCH: 1
01-25 14:50:48.908 10350 10350 W ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@8caed5c
01-25 14:50:48.996 10350 10350 E Parcel  : Class not found when unmarshalling: org.openintents.openpgp.OpenPgpError
01-25 14:50:48.996 10350 10350 E Parcel  : java.lang.ClassNotFoundException: org.openintents.openpgp.OpenPgpError
01-25 14:50:48.996 10350 10350 E Parcel  :      at java.lang.Class.classForName(Native Method)
01-25 14:50:48.996 10350 10350 E Parcel  :      at java.lang.Class.forName(Class.java:454)
01-25 14:50:48.996 10350 10350 E Parcel  :      at android.os.Parcel.readParcelableCreator(Parcel.java:3014)
01-25 14:50:48.996 10350 10350 E Parcel  :      at android.os.Parcel.readParcelable(Parcel.java:2964)
01-25 14:50:48.996 10350 10350 E Parcel  :      at android.os.Parcel.readValue(Parcel.java:2866)
01-25 14:50:48.996 10350 10350 E Parcel  :      at android.os.Parcel.readArrayMapInternal(Parcel.java:3244)
01-25 14:50:48.996 10350 10350 E Parcel  :      at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:292)
01-25 14:50:48.996 10350 10350 E Parcel  :      at android.os.BaseBundle.unparcel(BaseBundle.java:236)
01-25 14:50:48.996 10350 10350 E Parcel  :      at android.os.BaseBundle.getInt(BaseBundle.java:1035)
01-25 14:50:48.996 10350 10350 E Parcel  :      at android.content.Intent.getIntExtra(Intent.java:7835)
01-25 14:50:48.996 10350 10350 E Parcel  :      at com.zeapo.pwdstore.crypto.PgpActivity$decryptAndVerify$1$1.onReturn(PgpActivity.kt:1)
01-25 14:50:48.996 10350 10350 E Parcel  :      at me.msfjarvis.openpgpktx.util.OpenPgpApi$executeApiAsync$2.invokeSuspend(OpenPgpApi.kt:3)
01-25 14:50:48.996 10350 10350 E Parcel  :      at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:2)
01-25 14:50:48.996 10350 10350 E Parcel  :      at kotlinx.coroutines.DispatchedContinuation.run(Dispatched.kt:19)
01-25 14:50:48.996 10350 10350 E Parcel  :      at android.os.Handler.handleCallback(Handler.java:883)
01-25 14:50:48.996 10350 10350 E Parcel  :      at android.os.Handler.dispatchMessage(Handler.java:100)
01-25 14:50:48.996 10350 10350 E Parcel  :      at android.os.Looper.loop(Looper.java:214)
01-25 14:50:48.996 10350 10350 E Parcel  :      at android.app.ActivityThread.main(ActivityThread.java:7356)
01-25 14:50:48.996 10350 10350 E Parcel  :      at java.lang.reflect.Method.invoke(Native Method)
01-25 14:50:48.996 10350 10350 E Parcel  :      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
01-25 14:50:48.996 10350 10350 E Parcel  :      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
01-25 14:50:48.996 10350 10350 E Parcel  : Caused by: java.lang.ClassNotFoundException: org.openintents.openpgp.OpenPgpError
01-25 14:50:48.996 10350 10350 E Parcel  :      ... 21 more
01-25 14:50:48.997 10350 10538 E AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-1
01-25 14:50:48.997 10350 10538 E AndroidRuntime: Process: dev.msfjarvis.aps, PID: 10350
01-25 14:50:48.997 10350 10538 E AndroidRuntime: android.os.BadParcelableException: ClassNotFoundException when unmarshalling: org.openintents.openpgp.OpenPgpError
01-25 14:50:48.997 10350 10538 E AndroidRuntime:        at android.os.Parcel.readParcelableCreator(Parcel.java:3042)
01-25 14:50:48.997 10350 10538 E AndroidRuntime:        at android.os.Parcel.readParcelable(Parcel.java:2964)
01-25 14:50:48.997 10350 10538 E AndroidRuntime:        at android.os.Parcel.readValue(Parcel.java:2866)
01-25 14:50:48.997 10350 10538 E AndroidRuntime:        at android.os.Parcel.readArrayMapInternal(Parcel.java:3244)
01-25 14:50:48.997 10350 10538 E AndroidRuntime:        at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:292)
01-25 14:50:48.997 10350 10538 E AndroidRuntime:        at android.os.BaseBundle.unparcel(BaseBundle.java:236)
01-25 14:50:48.997 10350 10538 E AndroidRuntime:        at android.os.BaseBundle.getInt(BaseBundle.java:1035)
01-25 14:50:48.997 10350 10538 E AndroidRuntime:        at android.content.Intent.getIntExtra(Intent.java:7835)
01-25 14:50:48.997 10350 10538 E AndroidRuntime:        at com.zeapo.pwdstore.crypto.PgpActivity$decryptAndVerify$1$1.onReturn(PgpActivity.kt:1)
01-25 14:50:48.997 10350 10538 E AndroidRuntime:        at me.msfjarvis.openpgpktx.util.OpenPgpApi$executeApiAsync$2.invokeSuspend(OpenPgpApi.kt:3)
01-25 14:50:48.997 10350 10538 E AndroidRuntime:        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:2)
01-25 14:50:48.997 10350 10538 E AndroidRuntime:        at kotlinx.coroutines.DispatchedContinuation.run(Dispatched.kt:19)
01-25 14:50:48.997 10350 10538 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:883)
01-25 14:50:48.997 10350 10538 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:100)
01-25 14:50:48.997 10350 10538 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:214)
01-25 14:50:48.997 10350 10538 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7356)
01-25 14:50:48.997 10350 10538 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
01-25 14:50:48.997 10350 10538 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
01-25 14:50:48.997 10350 10538 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
01-25 14:50:48.999  1336 10543 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
01-25 14:50:48.999  1336  2236 W ActivityTaskManager:   Force finishing activity dev.msfjarvis.aps/com.zeapo.pwdstore.crypto.PgpActivity
```

**Comment by pdecat** [comment]
I get a few additional details when building `bug/openpgp-decrypt` branch in debug mode:

```
01-25 15:02:37.789  1336  1793 I ActivityTaskManager: START u0 {cmp=dev.msfjarvis.aps.debug/com.zeapo.pwdstore.crypto.PgpActivity (has extras)} from uid 10370
01-25 15:02:37.789   902   902 D android.hardware.power@1.3-service.pixel-libperfmgr: LAUNCH: 1
01-25 15:02:37.816 12830 12830 W ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@485fa38
01-25 15:02:37.997 12830 12830 E Parcel  : Class not found when unmarshalling: org.openintents.openpgp.OpenPgpError
01-25 15:02:37.997 12830 12830 E Parcel  : java.lang.ClassNotFoundException: org.openintents.openpgp.OpenPgpError
01-25 15:02:37.997 12830 12830 E Parcel  :      at java.lang.Class.classForName(Native Method)
01-25 15:02:37.997 12830 12830 E Parcel  :      at java.lang.Class.forName(Class.java:454)
01-25 15:02:37.997 12830 12830 E Parcel  :      at android.os.Parcel.readParcelableCreator(Parcel.java:3014)
01-25 15:02:37.997 12830 12830 E Parcel  :      at android.os.Parcel.readParcelable(Parcel.java:2964)
01-25 15:02:37.997 12830 12830 E Parcel  :      at android.os.Parcel.readValue(Parcel.java:2866)
01-25 15:02:37.997 12830 12830 E Parcel  :      at android.os.Parcel.readArrayMapInternal(Parcel.java:3244)
01-25 15:02:37.997 12830 12830 E Parcel  :      at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:292)
01-25 15:02:37.997 12830 12830 E Parcel  :      at android.os.BaseBundle.unparcel(BaseBundle.java:236)
01-25 15:02:37.997 12830 12830 E Parcel  :      at android.os.BaseBundle.getInt(BaseBundle.java:1035)
01-25 15:02:37.997 12830 12830 E Parcel  :      at android.content.Intent.getIntExtra(Intent.java:7835)
01-25 15:02:37.997 12830 12830 E Parcel  :      at com.zeapo.pwdstore.crypto.PgpActivity$decryptAndVerify$1$1.onReturn(PgpActivity.kt:252)
01-25 15:02:37.997 12830 12830 E Parcel  :      at me.msfjarvis.openpgpktx.util.OpenPgpApi$executeApiAsync$2.invokeSuspend(OpenPgpApi.kt:37)
01-25 15:02:37.997 12830 12830 E Parcel  :      at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
01-25 15:02:37.997 12830 12830 E Parcel  :      at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
01-25 15:02:37.997 12830 12830 E Parcel  :      at android.os.Handler.handleCallback(Handler.java:883)
01-25 15:02:37.997 12830 12830 E Parcel  :      at android.os.Handler.dispatchMessage(Handler.java:100)
01-25 15:02:37.997 12830 12830 E Parcel  :      at android.os.Looper.loop(Looper.java:214)
01-25 15:02:37.997 12830 12830 E Parcel  :      at android.app.ActivityThread.main(ActivityThread.java:7356)
01-25 15:02:37.997 12830 12830 E Parcel  :      at java.lang.reflect.Method.invoke(Native Method)
01-25 15:02:37.997 12830 12830 E Parcel  :      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
01-25 15:02:37.997 12830 12830 E Parcel  :      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
01-25 15:02:37.997 12830 12830 E Parcel  : Caused by: java.lang.ClassNotFoundException: Didn't find class "org.openintents.openpgp.OpenPgpError" on path: DexPathList[[zip file "/data/app/dev.msfjarvis.aps.debug-1xSW_jrxloKqh8pjyzzPog==/base.apk"],nativeLibraryDirectories=[/data/app/dev.msfjarvis.aps.debug-1xSW_jrxloKqh8pjyzzPog==/lib/arm64, /system/lib64, /product/lib64]]
01-25 15:02:37.997 12830 12830 E Parcel  :      at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
01-25 15:02:37.997 12830 12830 E Parcel  :      at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
01-25 15:02:37.997 12830 12830 E Parcel  :      at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
01-25 15:02:37.997 12830 12830 E Parcel  :      ... 21 more
01-25 15:02:38.004   902   902 D android.hardware.power@1.3-service.pixel-libperfmgr: LAUNCH: 0
01-25 15:02:38.058  1336  4250 W AppOps  : Noting op not finished: uid 10019 pkg com.google.android.gms code 79 time=1579960952548 duration=-1
01-25 15:02:38.059 12830 12863 E AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-1
01-25 15:02:38.059 12830 12863 E AndroidRuntime: Process: dev.msfjarvis.aps.debug, PID: 12830
01-25 15:02:38.059 12830 12863 E AndroidRuntime: android.os.BadParcelableException: ClassNotFoundException when unmarshalling: org.openintents.openpgp.OpenPgpError
01-25 15:02:38.059 12830 12863 E AndroidRuntime:        at android.os.Parcel.readParcelableCreator(Parcel.java:3042)
01-25 15:02:38.059 12830 12863 E AndroidRuntime:        at android.os.Parcel.readParcelable(Parcel.java:2964)
01-25 15:02:38.059 12830 12863 E AndroidRuntime:        at android.os.Parcel.readValue(Parcel.java:2866)
01-25 15:02:38.059 12830 12863 E AndroidRuntime:        at android.os.Parcel.readArrayMapInternal(Parcel.java:3244)
01-25 15:02:38.059 12830 12863 E AndroidRuntime:        at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:292)
01-25 15:02:38.059 12830 12863 E AndroidRuntime:        at android.os.BaseBundle.unparcel(BaseBundle.java:236)
01-25 15:02:38.059 12830 12863 E AndroidRuntime:        at android.os.BaseBundle.getInt(BaseBundle.java:1035)
01-25 15:02:38.059 12830 12863 E AndroidRuntime:        at android.content.Intent.getIntExtra(Intent.java:7835)
01-25 15:02:38.059 12830 12863 E AndroidRuntime:        at com.zeapo.pwdstore.crypto.PgpActivity$decryptAndVerify$1$1.onReturn(PgpActivity.kt:252)
01-25 15:02:38.059 12830 12863 E AndroidRuntime:        at me.msfjarvis.openpgpktx.util.OpenPgpApi$executeApiAsync$2.invokeSuspend(OpenPgpApi.kt:37)
01-25 15:02:38.059 12830 12863 E AndroidRuntime:        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
01-25 15:02:38.059 12830 12863 E AndroidRuntime:        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
01-25 15:02:38.059 12830 12863 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:883)
01-25 15:02:38.059 12830 12863 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:100)
01-25 15:02:38.059 12830 12863 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:214)
```

**Comment by pdecat** [comment]
Aren't debug builds not supposed to be proguarded at all?

**Comment by msfjarvis** [comment]
Okay I figured this out, wasn't a proguard bug after all. Give me a few minutes.

**Comment by msfjarvis** [comment]
> Aren't debug builds not supposed to be proguarded at all?

Yes they're completely unobfuscated. Release builds also disable obfuscation but retain minification for its tree shaking and other optimizations.

**Comment by msfjarvis** [comment]
#615 should be ready to go now @pdecat

**Comment by pdecat** [comment]
Pulled the latest changes and it no longer crashes, thanks!

Got another issue though.

**Comment by msfjarvis** [comment]
> Got another issue though.

Please file a separate issue for that :)

**Comment by pdecat** [comment]
Turns out the underlying error that was triggering the crash described in this issue is with a specific secret. Other secrets work fine.

Will dig this up and open an issue if needed...

```
01-25 15:46:54.488 15599 15599 E PgpActivity: onError getErrorId:Aucune donnée chiffrée avec une clé secrète connue n’a été trouvée dans le flux !
01-25 15:46:54.488 15599 15599 E PgpActivity: onError getMessage:Aucune donnée chiffrée avec une clé secrète connue n’a été trouvée dans le flux !
```

**Comment by pdecat** [comment]
For the record, my issue was caused by some secrets that did not have any recipient:

```
# gpg --list-only -v -d mybrokensecret.gpg
gpg: public key is 0x0000000000000000
gpg: encrypted with RSA key, ID 0x0000000000000000
```

Those secrets were created by gopass with the `throw-keyids` setting in `~/.gnupg/gpg.conf` as described in https://github.com/gopasspw/gopass/issues/1083#issuecomment-520881875

Running the following command on my main computer fixed all secrets:

```
# gopass fsck
```

**Comment by msfjarvis** [comment]
Good to know you sorted it out. There's a major change coming on the OpenKeychain side of things so maybe in the future we'll be able to align our behaviour with GPG and avoid the need for this.
