### ISSUE TITLE
[BUG] Type independent sort crash

### ISSUE THREAD

**Issue by imr0** [android-password-store/Android-Password-Store#733]
**Describe the bug**
Type independent sort crashes version 1.7.0 of the app

**To Reproduce**
1. Go to Settings
2. Change 'Password sort order' to 'Type independent'
3. Application crashes upon returning to the password list and immediately crashes on relaunch. 

**Expected behavior**
Provides type-agnostic, alphabetic sort of passwords without a crash. 

**Device information:**
 - Device: Google Pixel
 - OS: stock ROM Android version 10
 - App version 1.7.0

**Additional context**
Nothing else, besides wanting to express how much I love the app otherwise, especially the recent changes. Great work!

**Comment by msfjarvis** [comment]
:+1: Reproduced the crash

<details>
<summary>Stacktrace</summary>

```
java.lang.IllegalArgumentException: Failed requirement.
 at com.zeapo.pwdstore.SearchableRepositoryViewModelKt.access$makeComparator(SearchableRepositoryViewModel.kt:3)
 at com.zeapo.pwdstore.SearchableRepositoryViewModel.access$getItemComparator$p(SearchableRepositoryViewModel.kt:11)
 at com.zeapo.pwdstore.SearchableRepositoryViewModel$searchResult$1.invokeSuspend(SearchableRepositoryViewModel.kt:59)
 at com.zeapo.pwdstore.SearchableRepositoryViewModel$searchResult$1.invoke(Unknown Source:10)
 at kotlinx.coroutines.flow.FlowKtMergeKt$mapLatest$1.invokeSuspend(Merge.kt:2)
 at kotlinx.coroutines.flow.FlowKtMergeKt$mapLatest$1.invoke(Merge.kt:2)
 at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$invokeSuspend$$inlined$collect$1$lambda$1.invokeSuspend(Merge.kt:7)
 at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$invokeSuspend$$inlined$collect$1$lambda$1.invoke(Merge.kt:2)
 at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:5)
 at androidx.appcompat.app.AppCompatDelegateImpl$ConfigurationImplApi17.launch$default(AppCompatDelegateImpl.java:7)
 at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$invokeSuspend$$inlined$collect$1.emit(Collect.kt:20)
 at kotlinx.coroutines.flow.FlowKtDistinctKt$distinctUntilChangedBy$$inlined$distinctUntilChangedBy$FlowKtDistinctKt$1$2.emit(Collect.kt:11)
 at kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.invoke(SafeCollector.kt:1)
 at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:23)
 at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:1)
 at androidx.lifecycle.FlowLiveDataConversions$asFlow$1.invokeSuspend(FlowLiveData.kt:14)
 at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:2)
 at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:15)
 at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
 at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:12)
```

</details>

**Comment by FabianHenneke** [comment]
Thanks for the report! Sorry, I somehow assumed that `compareBy` without arguments would consider all elements as distinct, but it reliably runs into a `require` crash. #734 fixes this.

**Comment by imr0** [comment]
Thanks for the quick fix! ^^
