### ISSUE TITLE
[BUG] crashloop on GrapheneOS after granting EXTERNAL_STORAGE permission

### ISSUE THREAD

**Issue by Rudd-O** [android-password-store/Android-Password-Store#812]
```
05-30 15:53:54.304   978 11760 I ActivityManager: Process com.zeapo.pwdstore (pid 13843) has died: fore TOP 
05-30 15:53:54.305   978  1232 I libprocessgroup: Successfully killed process cgroup uid 10114 pid 13843 in 0ms
05-30 15:53:54.306   737   737 I Zygote  : Process 13843 exited due to signal 9 (Killed)
05-30 15:53:54.343   737   737 D Zygote  : Forked child process 13873
05-30 15:53:54.347   978  1231 I ActivityManager: Start proc 13873:com.zeapo.pwdstore/u0a114 for activity {com.zeapo.pwdstore/com.zeapo.pwdstore.PasswordStore}
05-30 15:53:54.357 13873 13873 E .zeapo.pwdstor: Not starting debugger since process cannot load the jdwp agent.
05-30 15:53:54.547 13873 13873 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 10114 <<<<<<
05-30 15:53:54.552 13873 13873 E libc    : Access denied finding property "persist.device_config.runtime_native_boot.enable_apex_image"
05-30 15:53:54.552 13873 13873 I AndroidRuntime: Using default boot image
05-30 15:53:54.552 13873 13873 E libc    : Access denied finding property "persist.device_config.runtime_native_boot.disable_lock_profiling"
05-30 15:53:54.552 13873 13873 I AndroidRuntime: Leaving lock profiling enabled
05-30 15:53:54.552 13873 13873 E libc    : Access denied finding property "persist.device_config.runtime_native_boot.enable_generational_cc"
05-30 15:53:54.671 13873 13873 D ICU     : Time zone APEX file found: /apex/com.android.tzdata/etc/icu/icu_tzdata.dat
05-30 15:53:54.705 13873 13873 W com.zeapo.pwdstore: JNI RegisterNativeMethods: attempt to register 0 native methods for android.media.AudioAttributes
05-30 15:53:54.712 13873 13873 D AndroidRuntime: Calling main entry com.android.internal.os.ExecInit
05-30 15:53:54.715 13873 13873 D Zygote  : begin preload
05-30 15:53:54.715 13873 13873 I Zygote  : Calling ZygoteHooks.beginPreload()
05-30 15:53:54.715 13873 13873 I Zygote  : Preloading shared libraries...
05-30 15:53:54.863 13873 13873 I Zygote  : Called ZygoteHooks.endPreload()
05-30 15:53:54.882 13873 13873 I Zygote  : Installed AndroidKeyStoreProvider in 20ms.
05-30 15:53:54.882 13873 13873 D Zygote  : end preload
05-30 15:53:54.933 13873 13873 W asset   : unable to execute idmap2: Permission denied
05-30 15:53:54.933 13873 13873 W AssetManager: 'idmap2 --scan' failed: no static="true" overlays targeting "android" will be loaded
05-30 15:53:54.928 13873 13873 W .zeapo.pwdstore: type=1400 audit(0.0:5973): avc: denied { execute } for name="idmap2" dev="dm-3" ino=705 scontext=u:r:untrusted_app:s0:c114,c256,c512,c768 tcontext=u:object_r:idmap_exec:s0 tclass=file permissive=0
05-30 15:53:54.967 13873 13901 D libEGL  : loaded /vendor/lib64/egl/libEGL_adreno.so
05-30 15:53:54.984 13873 13901 D libEGL  : loaded /vendor/lib64/egl/libGLESv1_CM_adreno.so
05-30 15:53:54.987 13873 13901 D libEGL  : loaded /vendor/lib64/egl/libGLESv2_adreno.so
05-30 15:53:55.052 13873 13873 D AndroidRuntime: Shutting down VM
05-30 15:53:55.054 13873 13873 E AndroidRuntime: FATAL EXCEPTION: main
05-30 15:53:55.054 13873 13873 E AndroidRuntime: Process: com.zeapo.pwdstore, PID: 13873
05-30 15:53:55.054 13873 13873 E AndroidRuntime: java.lang.RuntimeException: Unable to resume activity {com.zeapo.pwdstore/com.zeapo.pwdstore.PasswordStore}: java.lang.NullPointerException: Attempt to get length of null array
05-30 15:53:55.054 13873 13873 E AndroidRuntime: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4205)
05-30 15:53:55.054 13873 13873 E AndroidRuntime: 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4237)
05-30 15:53:55.054 13873 13873 E AndroidRuntime: 	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
05-30 15:53:55.054 13873 13873 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
05-30 15:53:55.054 13873 13873 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
05-30 15:53:55.054 13873 13873 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
05-30 15:53:55.054 13873 13873 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:107)
05-30 15:53:55.054 13873 13873 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
05-30 15:53:55.054 13873 13873 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7356)
05-30 15:53:55.054 13873 13873 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-30 15:53:55.054 13873 13873 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
05-30 15:53:55.054 13873 13873 E AndroidRuntime: 	at com.android.internal.os.ExecInit.main(ExecInit.java:43)
05-30 15:53:55.054 13873 13873 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
05-30 15:53:55.054 13873 13873 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:338)
05-30 15:53:55.054 13873 13873 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to get length of null array
05-30 15:53:55.054 13873 13873 E AndroidRuntime: 	at com.zeapo.pwdstore.utils.PasswordRepository.initialize(PasswordRepository.java:143)
05-30 15:53:55.054 13873 13873 E AndroidRuntime: 	at com.zeapo.pwdstore.PasswordStore.checkLocalRepository(PasswordStore.java:358)
05-30 15:53:55.054 13873 13873 E AndroidRuntime: 	at com.zeapo.pwdstore.PasswordStore.onResume(PasswordStore.java:156)
05-30 15:53:55.054 13873 13873 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1453)
05-30 15:53:55.054 13873 13873 E AndroidRuntime: 	at android.app.Activity.performResume(Activity.java:7962)
05-30 15:53:55.054 13873 13873 E AndroidRuntime: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4195)
05-30 15:53:55.054 13873 13873 E AndroidRuntime: 	... 13 more
05-30 15:53:55.055 13873 13873 E AndroidRuntime: Error reporting crash
05-30 15:53:55.055 13873 13873 E AndroidRuntime: java.lang.RuntimeException: Bad file descriptor
05-30 15:53:55.055 13873 13873 E AndroidRuntime: 	at android.os.BinderProxy.transactNative(Native Method)
05-30 15:53:55.055 13873 13873 E AndroidRuntime: 	at android.os.BinderProxy.transact(BinderProxy.java:511)
05-30 15:53:55.055 13873 13873 E AndroidRuntime: 	at android.app.IActivityManager$Stub$Proxy.handleApplicationCrash(IActivityManager.java:4655)
05-30 15:53:55.055 13873 13873 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$KillApplicationHandler.uncaughtException(RuntimeInit.java:145)
05-30 15:53:55.055 13873 13873 E AndroidRuntime: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1073)
05-30 15:53:55.055 13873 13873 E AndroidRuntime: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
05-30 15:53:55.055 13873 13873 E AndroidRuntime: 	at java.lang.Thread.dispatchUncaughtException(Thread.java:2187)
05-30 15:53:55.055 13873 13873 I Process : Sending signal. PID: 13873 SIG: 9
05-30 15:53:55.135   978  7493 I ActivityManager: Process com.zeapo.pwdstore (pid 13873) has died: fore TOP 
05-30 15:53:55.135   978  1232 I libprocessgroup: Successfully killed process cgroup uid 10114 pid 13873 in 0ms
05-30 15:53:55.137   737   737 I Zygote  : Process 13873 exited due to signal 9 (Killed)
05-30 15:53:55.173   737   737 D Zygote  : Forked child process 13903
05-30 15:53:55.181   978  1231 I ActivityManager: Start proc 13903:com.zeapo.pwdstore/u0a114 for activity {com.zeapo.pwdstore/com.zeapo.pwdstore.PasswordStore}
```

**Comment by Rudd-O** [comment]
Step by step:

1. Wizard at the beginning choice select external storage.
2. Folder selected.
3. Grant permission?  Yes.
4. App crashes (log above starts appearing in logcat).
5. Launching app again shows blank screen, log above repeats itself ad infinitum.

**Comment by Rudd-O** [comment]
Clearing app cache does not help.

GrapheneOS 29-05-2020.

Latest Password Store released on F-Droid.

**Comment by Rudd-O** [comment]
1.3.2 as released in the F-Droid store does not have this bug.

1.3.3 (latest) does.

**Comment by msfjarvis** [comment]
> 1.3.2 as released in the F-Droid store does not have this bug.
> 
> 1.3.3 (latest) does.

1.3.3 is not the latest build, 1.8.1 is. You can find binaries on the Play Store or GitHub releases.

**Comment by Rudd-O** [comment]
1.8.1 is not in F-Droid.

1.3.3 is.

**Comment by fmeum** [comment]
The current version on F-Droid is 1.9.2:
https://f-droid.org/en/packages/dev.msfjarvis.aps/

**Comment by Rudd-O** [comment]
Ah.  Something was broken about my F-Droid.  I have received the update and looks very nice!  Thank you.

**Comment by msfjarvis** [comment]
> Ah. Something was broken about my F-Droid. I have received the update and looks very nice! Thank you.

Thanks! Nothing was broken about your F-Droid, we simply had both the old and new listings up for a few versions and only recently got the old one removed due to all the confusion it has very evidently been causing.
